// Generated by gencpp from file gmfc/coordinate.msg
// DO NOT EDIT!


#ifndef GMFC_MESSAGE_COORDINATE_H
#define GMFC_MESSAGE_COORDINATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gmfc
{
template <class ContainerAllocator>
struct coordinate_
{
  typedef coordinate_<ContainerAllocator> Type;

  coordinate_()
    : message()
    , latitude(0.0)
    , longitude(0.0)  {
    }
  coordinate_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;





  typedef boost::shared_ptr< ::gmfc::coordinate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmfc::coordinate_<ContainerAllocator> const> ConstPtr;

}; // struct coordinate_

typedef ::gmfc::coordinate_<std::allocator<void> > coordinate;

typedef boost::shared_ptr< ::gmfc::coordinate > coordinatePtr;
typedef boost::shared_ptr< ::gmfc::coordinate const> coordinateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmfc::coordinate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmfc::coordinate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gmfc::coordinate_<ContainerAllocator1> & lhs, const ::gmfc::coordinate_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gmfc::coordinate_<ContainerAllocator1> & lhs, const ::gmfc::coordinate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gmfc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gmfc::coordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmfc::coordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmfc::coordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmfc::coordinate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmfc::coordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmfc::coordinate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmfc::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36ac278e1f13c9951d4d6498c308eba5";
  }

  static const char* value(const ::gmfc::coordinate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36ac278e1f13c995ULL;
  static const uint64_t static_value2 = 0x1d4d6498c308eba5ULL;
};

template<class ContainerAllocator>
struct DataType< ::gmfc::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmfc/coordinate";
  }

  static const char* value(const ::gmfc::coordinate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmfc::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"float32 latitude\n"
"float32 longitude\n"
;
  }

  static const char* value(const ::gmfc::coordinate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmfc::coordinate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordinate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmfc::coordinate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmfc::coordinate_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMFC_MESSAGE_COORDINATE_H
